In [34]:
import numpy as np

In [35]:
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [36]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


In [37]:
b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]

[ 5. 10. 15. 20. 25.]


In [38]:
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5

5


In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # [ 4 10 18]

[ 4 10 18]


In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32

32


In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(b / a)  # [4.  2.5 2. ]

[4.  2.5 2. ]


In [43]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


In [44]:
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)  # (5,)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)  # (2, 3

(5,)
(2, 3)


In [45]:
a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])

b = np.array([[2, 2, 2, 2],
              [1, 1, 1, 1]])

print(a*b)

[[ 4  6  8 10]
 [ 1  2  3  4]]


In [46]:
a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

c = np.dot(a, b)
print(c)

[[-2 10]
 [-2  4]]


In [47]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


In [49]:
a = np.eye(4, k=-1, dtype=float)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [50]:
a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


In [51]:
a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [52]:
a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [53]:
a = np.arange(5)
b = np.arange(1, 4, 0.5)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5 3.  3.5]


In [54]:
a = np.linspace(1, 5, num=5)
b = np.linspace(1, 81, num=9)
print(a)
print(b)

[1. 2. 3. 4. 5.]
[ 1. 11. 21. 31. 41. 51. 61. 71. 81.]


наповнення матриці випадковими числами

In [33]:
a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print(b)

[0.69782084 0.87637289 0.81088317]
[[0.67091079 0.71617197 0.86703871]
 [0.31313532 0.96842971 0.5573107 ]
 [0.60119073 0.45972347 0.62898067]]


In [57]:
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[2:])
print(a[:3])

1
[3 4 5]
[1 2 3]


In [58]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


In [59]:
b = np.zeros((3, 3), dtype="u4")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [60]:
a = np.array([u"\u2211", u"\u220F"], dtype="U")
print(a)  # ['∑' '∏']

['∑' '∏']


In [61]:
a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
5
15
3.0
120


In [62]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
9
45
5.0
362880
